version: "3.9"

services:
  db:
    image: postgres:15
    container_name: beautyai_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mojehaslo
      POSTGRES_DB: beautyai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile   # ✅ tu jest zmiana!
    container_name: beautyai_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mojehaslo@db:5432/beautyai
    volumes:
      - ./backend:/app/backend

volumes:
  pgdata:
